version: "3.6"
services:
  db:
    image: postgres:11
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=polycade
    container_name: "postgres-container"
    ports:
      - "54320:5432"
    tmpfs: /var/lib/postgresql/data